### ISSUE TITLE
Can the code run with   win10 + Python 3.7+tensorflow 1.31? Thank you

### ISSUE THREAD

**Issue by QQ2737499951** [rohitsaluja22/OCR-On-the-go#1]
Can the code run with   win10 + Python 3.7+tensorflow 1.31? Thank you

**Comment by rohitsaluja22** [comment]
Thanks for your interest. We have included the comments with the phrase "OCR-on-the-go" everywhere we have modified the original attention_ocr code. You will have to modify the original attention_ocr code and include our code as per your requirements. It should be doable but would need a lot of modifications as per tensorflow 1.37 and python3.7.
