### ISSUE TITLE
"charset_filename"

### ISSUE THREAD

**Issue by nhattruongpham** [rohitsaluja22/OCR-On-the-go#4]
Hi sir,
Where is "charset_sizeNPR.txt/charset_sizeDev.txt"?
Many thanks!

**Comment by rohitsaluja22** [comment]
Attached them here
[charset_sizeNPR.txt](https://github.com/rohitsaluja22/OCR-On-the-go/files/3987047/charset_sizeNPR.txt)
[charset_sizeDev.txt](https://github.com/rohitsaluja22/OCR-On-the-go/files/3987048/charset_sizeDev.txt)
